#!/usr/bin/env python3
"""Regenerate everything under data/ from the upstream sources.

    python3 tools/build.py            # download what's missing, then build
    python3 tools/build.py --offline  # build from an already-populated cache

Downloads land in tools/cache/ (about 1.6 GB) and are not committed; only the
generated JSON under data/ is.

The reading texts come from the LASLA *Opera Latina* corpus, which covers
Caesar, Cicero and Tacitus complete. The works are listed in lasla_works.py;
their books and section numbers come from the data's own citation hierarchy,
so adding an author is a matter of adding a table there and downloading the
matching files.

Two works are not in LASLA, or in any other annotated corpus: De Re Publica
and De Legibus. Their text comes from Perseus and The Latin Library, and their
morphology is generated by tools/annotate.py, which has to be run once by hand
because it needs a tagger and a model the rest of the build does not. The
reader labels them as machine-annotated.

tools/build_text.py still reads the Perseus treebank; that corpus is a
twentieth of the size but carries dependency annotation LASLA lacks. It is
kept for reference and is not called from here.
"""

import glob
import json
import os
import re
import subprocess
import sys
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lasla
import lasla_works

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CACHE = os.path.join(HERE, "cache")
DATA = os.path.join(ROOT, "data")
LASLA_DIR = os.path.join(CACHE, "lasla")
AUTO_DIR = os.path.join(CACHE, "auto")

LASLA_API = ("https://api.github.com/repos/CIRCSE/LASLA/contents/"
             "conllup?per_page=300")
# Perseus ships two copies of Lewis & Short; -eng2 is the same dictionary with
# tidier markup and real Unicode Greek, so one file is all we need.
LS_URL = ("https://raw.githubusercontent.com/PerseusDL/lexica/master/"
          "CTS_XML_TEI/perseus/pdllex/lat/ls/lat.ls.perseus-eng2.xml")
WIKT_URL = "https://kaikki.org/dictionary/Latin/kaikki.org-dictionary-Latin.jsonl"

AUTHORS = {k: latin for k, latin, _ in lasla_works.AUTHORS}

NOTE = ("LASLA lemmatises words only, so the text is unpunctuated, and it "
        "keeps the classical orthography in which consonantal v is written u "
        "(Seruius, diuisa). Section numbers are the corpus's own and are "
        "canonical.")

AUTO_NOTE = ("Automated morphology. No hand-checked annotation of this work "
             "exists, so the parses and dictionary forms here were generated "
             "by the LatinCy tagger and have not been verified — expect them "
             "to be wrong now and then, most often where the Latin is "
             "genuinely ambiguous. The text is from %s, respelled with u for "
             "consonantal v to match the rest of the site.")

AUTO_SOURCE = {
    "DeRePublica": "the Perseus Digital Library",
    "DeLegibus": "The Latin Library",
}


def fetch(url, dest):
    if os.path.exists(dest) and os.path.getsize(dest) > 0:
        return
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    print("downloading", os.path.basename(dest), flush=True)
    tmp = dest + ".part"
    urllib.request.urlretrieve(url, tmp)
    os.replace(tmp, dest)


def fetch_lasla():
    """Pull down every conllup file belonging to one of our authors."""
    os.makedirs(LASLA_DIR, exist_ok=True)
    with urllib.request.urlopen(LASLA_API) as fh:
        listing = json.load(fh)
    for item in listing:
        if item["name"].split("_")[0] not in AUTHORS:
            continue
        fetch(item["download_url"], os.path.join(LASLA_DIR, item["name"]))


def files_for(author, work_key):
    root = AUTO_DIR if work_key in lasla_works.MACHINE else LASLA_DIR
    pat = os.path.join(root, "%s_%s_*.conllup" % (author, work_key))
    return sorted(glob.glob(pat))


def main():
    offline = "--offline" in sys.argv
    wikt = os.path.join(CACHE, "wiktionary-lat.jsonl")
    ls_dir = os.path.join(CACHE, "ls")

    if not offline:
        fetch_lasla()
        fetch(WIKT_URL, wikt)
        fetch(LS_URL, os.path.join(ls_dir, "ls02.xml"))

    for path in (wikt, ls_dir, LASLA_DIR):
        if not os.path.exists(path):
            sys.exit("missing source: %s (run without --offline)" % path)

    index = []
    grand = 0
    for author, author_latin, work_key, wid, latin, english, ref, noun in \
            lasla_works.index():
        srcs = files_for(author, work_key)
        if not srcs:
            print("  skipping %s (no files cached)" % wid)
            continue
        auto = work_key in lasla_works.MACHINE
        out = os.path.join(DATA, wid)
        divisions = []
        for src in srcs:
            divisions += lasla.build(src, out, auto=auto)
        divisions.sort(key=lambda d: d["n"])
        # The scrappier fragments carry no citation hierarchy at all, so there
        # is nothing to number them by and nothing to render. Leave them out
        # rather than list a work that opens empty.
        if not divisions:
            print("  skipping %s (no citable text)" % wid)
            continue
        tokens = sum(d["tokens"] for d in divisions)
        grand += tokens
        print("%-24s %-38s %2d %s, %6d words%s"
              % (author, latin[:38], len(divisions), noun.lower() + "s", tokens,
                 "  [machine-annotated]" if auto else ""))
        entry = {
            "id": wid, "author": author, "authorLatin": author_latin,
            "title": english, "latin": latin, "label": english, "ref": ref,
            "scheme": "ud", "unit": "section", "noun": noun,
            "note": AUTO_NOTE % AUTO_SOURCE[work_key] if auto else NOTE,
            "divisions": [{"n": d["n"], "units": d["units"], "first": d["first"]}
                          for d in divisions],
        }
        if auto:
            entry["auto"] = True
        index.append(entry)

    # Declaration order in lasla_works, not alphabetical: it puts the works
    # people come for first, so the site opens on the Gallic War rather than
    # the Civil War and Cicero starts at the Catilinarians.
    order = {row[3]: i for i, row in enumerate(lasla_works.index())}
    index.sort(key=lambda w: order[w["id"]])
    print("\n%d works, %s words" % (len(index), format(grand, ",")))

    # One lexicon serves every work, so feed it the union of their lemmas.
    lemmas = set()
    for path in glob.glob(os.path.join(DATA, "*", "book-*.json")):
        with open(path, encoding="utf-8") as fh:
            lemmas.update(l for l in json.load(fh)["lemmas"] if l)
    union = os.path.join(DATA, "lemmas.txt")
    with open(union, "w", encoding="utf-8") as fh:
        fh.write("\n".join(sorted(lemmas)))
    print("\n--- lexicon (%s distinct lemmas) ---" % format(len(lemmas), ","),
          flush=True)
    subprocess.check_call(
        [sys.executable, os.path.join(HERE, "build_lexicon.py"), union, ls_dir,
         wikt, os.path.join(DATA, "lexicon.json")], cwd=HERE)

    with open(os.path.join(DATA, "works.json"), "w", encoding="utf-8") as fh:
        json.dump({"works": index}, fh, ensure_ascii=False, indent=1)
    print("\ndone — data/ regenerated")


if __name__ == "__main__":
    main()
